---
- name: Uninstall MongoDB Router Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    autoremove: yes
    autoclean: yes
    purge: yes
    state: absent
  with_items:
    - percona-server-mongodb-{{ mongo_version_major }}{{ mongo_version_minor }}-mongos
    - percona-server-mongodb-{{ mongo_version_major }}{{ mongo_version_minor }}-shell
    - percona-server-mongodb-{{ mongo_version_major }}{{ mongo_version_minor }}-tools
  when:
    - mongo_distribution == 'percona'
    - inventory_hostname in groups['mongos']

- name: Uninstall MongoDB Node Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    autoremove: yes
    autoclean: yes
    purge: yes
    state: absent
  with_items:
    - percona-server-mongodb-{{ mongo_version_major }}{{ mongo_version_minor }}-server
    - percona-server-mongodb-{{ mongo_version_major }}{{ mongo_version_minor }}-shell
    - percona-server-mongodb-{{ mongo_version_major }}{{ mongo_version_minor }}-tools
  when:
    - mongo_distribution == 'percona'
    - inventory_hostname not in groups['mongos']

- name: Uninstall MongoDB Repository
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    autoremove: yes
    autoclean: yes
    purge: yes
    state: absent
  with_items:
    - percona-release
  when:
    - mongo_distribution == 'percona'
