---
- name: Install Python PIP Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    autoclean: yes
    state: present
  with_items:
    - python-pip

- name: Install PyMongo Packages from Python PIP
  pip:
    name: pymongo
    state: latest
    use_mirrors: no
